export const CITY_INPUT_VALUE = "CITY_INPUT_VALUE";
export const WEATHER_FOR_FEW_DAYS = "WEATHER_FOR_FEW_DAYS";
export const RESET_WEATHER = "RESET_WEATHER";
export const END_LOADING = "END_LOADING";
export const START_LOADING = "START_LOADING";
export const END_LOADING_FOR_MORE_WEATHER_SCREEN = "END_LOADING_FOR_MORE_WEATHER_SCREEN";
export const START_LOADING_FOR_MORE_WEATHER_SCREEN = "START_LOADING_FOR_MORE_WEATHER_SCREEN";